// Generated by CoffeeScript 1.10.0
$(function() {
  var full, showIcon, toc, up;
  up = $('.icon-arrow-up');
  up.click(function() {
    $('html, body, .fullscreen').animate({
      scrollTop: 0
    }, 1000);
  });
  showIcon = function(top) {
    if (top > 1000) {
      up.show();
    } else {
      up.hide();
    }
  };
  $(window).scroll(function() {
    showIcon($(this).scrollTop());
  });
  toc = $('article.toc');
  if ('' === toc.html()) {
    $('.icon-toc').hide();
  }
  $(document).on('opening', '[data-remodal-id=comment]', function() {
    $.getScript('//static.duoshuo.com/embed.js');
  });
  full = $('.icon-fullscreen');
  full.click(function(e) {
    screenfull.toggle('', function(isFullscreen) {
      if (!isFullscreen) {
        full.attr('title', '全屏').addClass('icon-fullscreen').removeClass('icon-screenshot');
      } else {
        full.attr('title', '取消全屏').addClass('icon-screenshot').removeClass('icon-fullscreen');
      }
    });
  });
  $(function() {
    var arr_path, arr_url, path, url;
    path = window.location.pathname;
    arr_path = path.split('/');
    arr_url = arr_path.slice(0, 2);
    url = '//' + window.location.host + arr_url.join('/') + '/summary/index.json';
    $.getJSON(url, function(json) {
      var file_name, option;
      $('article.summary').html(json.summary);
      $('article.summary blockquote').hide();
      option = $('article.summary a[href="' + path + '"]');
      file_name = option.html();
      option.html('<span style="color:orange">' + file_name + '</span>');
      if (option.parent().prev().length) {
        $('.icon-prev').html(option.parent().prev().html());
        $('.icon-prev a').html('');
      } else {
        $('.icon-prev').hide();
      }
      if (option.parent().next().length) {
        $('.icon-next').html(option.parent().next().html());
        $('.icon-next a').html('');
      } else {
        $('.icon-next').hide();
      }
    });
  });
});

screenfull.toggle = function(elem, fn) {
  if (this.isFullscreen) {
    this.exit();
    fn(false);
  } else {
    this.request(elem);
    fn(true);
  }
};
